-- phpMyAdmin SQL Dump
-- version 4.9.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Tempo de geração: 06/08/2020 às 11:36
-- Versão do servidor: 5.6.41-84.1
-- Versão do PHP: 7.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `sapienza_perfexcrm`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `tblemailtemplates`
--

CREATE TABLE `tblemailtemplates` (
  `emailtemplateid` int(11) NOT NULL,
  `type` mediumtext NOT NULL,
  `slug` varchar(100) NOT NULL,
  `language` varchar(40) DEFAULT NULL,
  `name` mediumtext NOT NULL,
  `subject` mediumtext NOT NULL,
  `message` text NOT NULL,
  `fromname` mediumtext NOT NULL,
  `fromemail` varchar(100) DEFAULT NULL,
  `plaintext` int(11) NOT NULL DEFAULT '0',
  `active` tinyint(4) NOT NULL DEFAULT '0',
  `order` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Despejando dados para a tabela `tblemailtemplates`
--

INSERT INTO `tblemailtemplates` (`emailtemplateid`, `type`, `slug`, `language`, `name`, `subject`, `message`, `fromname`, `fromemail`, `plaintext`, `active`, `order`) VALUES
(1315, 'client', 'new-client-created', 'portuguese_br', 'New Contact Added/Registered (Welcome Email) [portuguese_br]', 'Bem vindo à bordo!', 'Caro(a) {contact_firstname} {contact_lastname},<br /><br />Obrigado por se tornar um cliente. Gostaria de te dar as boas-vindas!<br /><br />Por favor, n&atilde;o hesite em me contactar se houver qualquer d&uacute;vida, solicita&ccedil;&atilde;o, sugest&atilde;o, reclama&ccedil;&atilde;o, modifica&ccedil;&atilde;o ou novos servi&ccedil;os.<br /><br />Para solicitar novos servi&ccedil;os ou ajuda t&eacute;cnica, acesse a <a href=\"https://crm.sapienzae.com.br\" target=\"_blank\" rel=\"noopener\" title=\"Ir para a &Aacute;rea do Cliente\">&aacute;rea do cliente</a> -&gt; Solicita&ccedil;&otilde;es -&gt; Nova Solicita&ccedil;&atilde;o.<br /><br />&Agrave; partir de uma solicita&ccedil;&atilde;o, poderei criar projetos, tarefas e faturas (se aplic&aacute;vel) para atender &agrave;s suas necessidades, e voc&ecirc; poder&aacute; acompanhar o andamento de todo o processo por l&aacute;.<br /><br />De qualquer forma, anote meu e-mail pessoal e WhatsApp, e sinta-se &agrave; vontade para entrar em contato comigo diretamente, havendo necessidade:<br /><br />\r\n<ul>\r\n<li>Email: alex@sapienzae.com.br</li>\r\n<li>WhatsApp: (79) 99876-0333</li>\r\n</ul>\r\n<br />(Esta &eacute; uma mensagem autom&aacute;tica, por favor n&atilde;o responda &agrave; este email)<br /><br />Com muita satisfa&ccedil;&atilde;o, <br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1316, 'invoice', 'invoice-send-to-client', 'portuguese_br', 'Send Invoice to Customer [portuguese_br]', 'Fatura de número {invoice_number} criada', '<span style=\"font-size: 12pt;\">Caro(a) {contact_firstname} {contact_lastname},</span><br /><br /><span style=\"font-size: 12pt;\">A fatura de n&uacute;mero&nbsp;<strong># {invoice_number}</strong> foi criada.</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Status da Fatura</strong>: {invoice_status}</span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; pode ver e pagar a fatura no seguinte link: <a href=\"{invoice_link}\">{invoice_number}</a></span><br /><br /><span style=\"font-size: 12pt;\">Por favor entre em contato conosco em caso de d&uacute;vidas.</span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1317, 'ticket', 'new-ticket-opened-admin', 'portuguese_br', 'New Ticket Opened (Opened by Staff, Sent to Customer) [portuguese_br]', 'Nova solicitação aberta', '<span style=\"font-size: 12pt;\">Ol&aacute; {contact_firstname} {contact_lastname},</span><br /><br /><span style=\"font-size: 12pt;\">Uma nova solicita&ccedil;&atilde;o foi aberta.</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Assunto:</strong> {ticket_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Departmento:</strong> {ticket_department}</span><br /><span style=\"font-size: 12pt;\"><strong>Prioridade:</strong> {ticket_priority}</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Mensagem:</strong></span><br /><span style=\"font-size: 12pt;\">{ticket_message}</span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; pode acompanhar sua solicita&ccedil;&atilde;o no seguinte link link: <a href=\"{ticket_url}\">#{ticket_id}<br /><br /></a>Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1318, 'ticket', 'ticket-reply', 'portuguese_br', 'Ticket Reply (Sent to Customer) [portuguese_br]', 'Nova Resposta à Solicitação', '<span style=\"font-size: 12pt;\">Ol&aacute; {contact_firstname} {contact_lastname},</span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; tem uma nova resposta na solicita&ccedil;&atilde;o&nbsp;<a href=\"{ticket_url}\">#{ticket_id}</a></span><br /><br /><span style=\"font-size: 12pt;\"><strong>Assunto da Solicita&ccedil;&atilde;o:</strong> {ticket_subject}<br /></span><br /><span style=\"font-size: 12pt;\"><strong>Mensagem:</strong></span><br /><span style=\"font-size: 12pt;\">{ticket_message}</span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; pode acompanhar a solicita&ccedil;&atilde;o no seguinte link: <a href=\"{ticket_url}\">#{ticket_id}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1319, 'ticket', 'ticket-autoresponse', 'portuguese_br', 'New Ticket Opened - Autoresponse [portuguese_br]', 'Nova Solicitação Aberta', '<span style=\"font-size: 12pt;\">Ol&aacute; {contact_firstname} {contact_lastname},</span><br /><br /><span style=\"font-size: 12pt;\">Obrigado por sua solicita&ccedil;&atilde;o. Irei responder em breve e voc&ecirc; ser&aacute; notificado via e-mail.</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Assunto:</strong> {ticket_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Departmento</strong>: {ticket_department}</span><br /><span style=\"font-size: 12pt;\"><strong>Prioridade:</strong> {ticket_priority}</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Mensagem:</strong></span><br /><span style=\"font-size: 12pt;\">{ticket_message}</span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; pode acompanhar sua solicita&ccedil;&atilde;o no seguinte link: <a href=\"{ticket_url}\">#{ticket_id}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1320, 'invoice', 'invoice-payment-recorded', 'portuguese_br', 'Invoice Payment Recorded (Sent to Customer) [portuguese_br]', 'Confirmação de Pagemento de Fatura', '<span style=\"font-size: 12pt;\">Ol&aacute; {contact_firstname}&nbsp;{contact_lastname},<br /><br /></span>Obrigado pelo pagamento. Seguem detalhes:<br /><br />-------------------------------------------------<br /><br />Valor:&nbsp;<strong>{payment_total}<br /></strong>Data:&nbsp;<strong>{payment_date}</strong><br />N&uacute;mero da fatura:&nbsp;<span style=\"font-size: 12pt;\"><strong># {invoice_number}<br /><br /></strong></span>-------------------------------------------------<br /><br />Voc&ecirc; pode sempre ver a fatura pelo seguinte link:&nbsp;<a href=\"{invoice_link}\"><span style=\"font-size: 12pt;\">{invoice_number}</span></a><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1321, 'invoice', 'invoice-overdue-notice', 'portuguese_br', 'Invoice Overdue Notice [portuguese_br]', 'Aviso de Atraso de Fatura - {invoice_number}', '<span style=\"font-size: 12pt;\">Ol&aacute; {contact_firstname} {contact_lastname},</span><br /><br /><span style=\"font-size: 12pt;\">Este &eacute; um aviso de que a fatura&nbsp;<strong># {invoice_number}</strong> est&aacute; em atraso.</span><br /><br /><span style=\"font-size: 12pt;\">A fatura venceu em: {invoice_duedate}</span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; pode ver detalhes e pagar a fatura no seguinte link: <a href=\"{invoice_link}\">{invoice_number}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1322, 'invoice', 'invoice-already-send', 'portuguese_br', 'Invoice Already Sent to Customer [portuguese_br]', 'Fatura # {invoice_number} ', '<span style=\"font-size: 12pt;\">Ol&aacute; {contact_firstname} {contact_lastname},</span><br /><br /><span style=\"font-size: 12pt;\">Conforme solicitado, segue fatura n&uacute;mero <strong># {invoice_number}</strong></span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; pode visualizar a fatura no seguinte link: <a href=\"{invoice_link}\">{invoice_number}</a></span><br /><br /><span style=\"font-size: 12pt;\">Por favor entre em contato conosco em caso de d&uacute;vidas.</span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1323, 'ticket', 'new-ticket-created-staff', 'portuguese_br', 'New Ticket Created (Opened by Customer, Sent to Staff Members) [portuguese_br]', 'Nova Solicitação Criada', '<span style=\"font-size: 12pt;\">Uma nova solicita&ccedil;&atilde;o foi aberta.<br /><br /><strong>Assunto</strong>: {ticket_subject}<br /><strong>Departmento</strong>: {ticket_department}<br /><strong>Prioridade</strong>: {ticket_priority}<br /><br /><strong>Mensagem:</strong><br />{ticket_message}<br /><br />Voc&ecirc; pode acompanhar sua solicita&ccedil;&atilde;o no seguinte link: <a href=\"{ticket_url}\">#{ticket_id}<br /></a><br />Atenciosamente,<br />{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1324, 'estimate', 'estimate-send-to-client', 'portuguese_br', 'Send Estimate to Customer [portuguese_br]', 'Orçamento # {estimate_number} criado', '<span style=\"font-size: 12pt;\">Caro(a) {contact_firstname} {contact_lastname},</span><br /><br /><span style=\"font-size: 12pt;\">Segue em anexo o or&ccedil;amento&nbsp;<strong># {estimate_number}</strong></span><br /><br /><span style=\"font-size: 12pt;\"><strong>Status do Or&ccedil;amento:</strong> {estimate_status}</span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; pode aprovar o or&ccedil;amento no seguinte link: <a href=\"{estimate_link}\">{estimate_number}</a></span><br /><br /><span style=\"font-size: 12pt;\">Aguardo seu contato,</span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}<br /></span>', '{companyname} | CRM', '', 0, 1, 0),
(1325, 'ticket', 'ticket-reply-to-admin', 'portuguese_br', 'Ticket Reply (Sent to Staff) [portuguese_br]', 'Nova Resposta à Solicitação', '<span style=\"font-size: 12pt;\">Uma nova resposta &agrave; solicita&ccedil;&atilde;o de {contact_firstname} {contact_lastname}.<br /><br /><strong>Assunto</strong>: {ticket_subject}<br /><strong>Departmento</strong>: {ticket_department}<br /><strong>Prioridade</strong>: {ticket_priority}<br /><br /><strong>Mensagem:</strong><br />{ticket_message}<br /><br />Voc&ecirc; pode acompanhar a solicita&ccedil;&atilde;o no seguinte link: <a href=\"{ticket_url}\">#{ticket_id}</a><br /><br />Atenciosamente,<br />{email_signature}<br /></span>', '{companyname} | CRM', '', 0, 1, 0),
(1326, 'estimate', 'estimate-already-send', 'portuguese_br', 'Estimate Already Sent to Customer [portuguese_br]', 'Orçamento # {estimate_number} ', '<span style=\"font-size: 12pt;\">Caro(a) {contact_firstname} {contact_lastname},</span><br /><br /><span style=\"font-size: 12pt;\">Obrigado por sua solicita&ccedil;&atilde;o de or&ccedil;amento.</span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; pode ver o or&ccedil;amento no seguinte link: <a href=\"{estimate_link}\">{estimate_number}</a></span><br /><br /><span style=\"font-size: 12pt;\">Aguardo seu contato.</span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1327, 'contract', 'contract-expiration', 'portuguese_br', 'Contract Expiration Reminder (Sent to Customer Contacts) [portuguese_br]', 'Lembrete de vencimento do contrato', '<span style=\"font-size: 12pt;\">Prezado(a) {client_company}</span><br /><br />Este &eacute; um lembrete de que o contrato a seguir expirar&aacute; em breve:<br /><br /><span style=\"font-size: 12pt;\"><strong>Assunto:</strong> {contract_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Descri&ccedil;&atilde;o:</strong> {contract_description}</span><br /><span style=\"font-size: 12pt;\"><strong>Data de In&iacute;cio:</strong> {contract_datestart}</span><br /><span style=\"font-size: 12pt;\"><strong>Data de Concus&atilde;o:</strong> {contract_dateend}</span><br /><br />Entre em contato conosco para mais informa&ccedil;&otilde;es.<br /><br /><span style=\"font-size: 12pt;\">Sauda&ccedil;&otilde;es,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1328, 'tasks', 'task-assigned', 'portuguese_br', 'New Task Assigned (Sent to Staff) [portuguese_br]', 'Nova Tarefa designada à você - {task_name}', '<span style=\"font-size: 12pt;\">Caro(a) {staff_firstname},</span><br /><br /><span style=\"font-size: 12pt;\">Uma nova tarefa foi designada &agrave; voc&ecirc;:</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Nome:</strong> {task_name}<br /></span><strong>Data de In&iacute;cio:</strong> {task_startdate}<br /><span style=\"font-size: 12pt;\"><strong>Data limite:</strong> {task_duedate}</span><br /><span style=\"font-size: 12pt;\"><strong>Prioridade:</strong> {task_priority}<br /><br /></span><span style=\"font-size: 12pt;\"><span>Voc&ecirc; pode ver a tarefa no seguinte link</span>: <a href=\"{task_link}\">{task_name}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1329, 'tasks', 'task-added-as-follower', 'portuguese_br', 'Staff Member Added as Follower on Task (Sent to Staff) [portuguese_br]', 'Você foi adicionaro como seguidor numa tarefa - {task_name}', '<span style=\"font-size: 12pt;\"><span>Caro(a) {staff_firstname},<br /><br />Voc&ecirc; foi adicionado como seguidor na seguinte tarefa:<br /><br /><strong>Nome:</strong> {task_name}<br /><strong>Data de in&iacute;cio:</strong> {task_startdate}<br /><br />Voc&ecirc; pode ver a tarefa no seguinte link</span>: <a href=\"{task_link}\">{task_name}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1330, 'tasks', 'task-commented', 'portuguese_br', 'New Comment on Task (Sent to Staff) [portuguese_br]', 'Novo comentário em tarefa - {task_name}', '<span style=\"font-size: 12pt;\"><span>Caro(a) {staff_firstname},<br /><br />Um coment&aacute;rio foi feito na seguinte tarefa:<br /><br /><strong>Nome:</strong> {task_name}<br /><strong>Coment&aacute;rio:</strong> {task_comment}<br /><br />Voc&ecirc; pode ver a tarefa no seguinte link</span>: <a href=\"{task_link}\">{task_name}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1331, 'tasks', 'task-added-attachment', 'portuguese_br', 'New Attachment(s) on Task (Sent to Staff) [portuguese_br]', 'Novo anexo em tarefa - {task_name}', '<span style=\"font-size: 12pt;\"><span>Caro(a) {staff_firstname},<br /><br /><strong>{task_user_take_action}</strong>&nbsp;adicionou um anexo na seguinte tarefa:<br /><br /><strong>Nome:</strong> {task_name}<br /><br />Voc&ecirc; pode ver a tarefa no seguinte link</span>: <a href=\"{task_link}\">{task_name}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1332, 'estimate', 'estimate-declined-to-staff', 'portuguese_br', 'Estimate Declined (Sent to Staff) [portuguese_br]', 'Cliente Negou Orçamento', '<span style=\"font-size: 12pt;\">Ol&aacute;,<br /><br />O cliente ({client_company}) negou o or&ccedil;amento&nbsp;<strong># {estimate_number}</strong><br /><br />Voc&ecirc; pode ver o or&ccedil;amento no seguinte link: <a href=\"{estimate_link}\">{estimate_number}</a></span><br /><br /><span style=\"font-size: 12pt;\">Aguardo seu contato.</span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1333, 'estimate', 'estimate-accepted-to-staff', 'portuguese_br', 'Estimate Accepted (Sent to Staff) [portuguese_br]', 'Cliente Aceitou Orçamento', '<span style=\"font-size: 12pt;\">Hi<br /><br />O cliente ({client_company}) aceitou o or&ccedil;amento de n&uacute;mero&nbsp;<strong># {estimate_number}</strong><br /><br />Voc&ecirc; pode ver o or&ccedil;amento no seguinte link: <a href=\"{estimate_link}\">{estimate_number}</a></span><br /><br /><span style=\"font-size: 12pt;\">Aguardo seu contato.</span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1334, 'proposals', 'proposal-client-accepted', 'portuguese_br', 'Customer Action - Accepted (Sent to Staff) [portuguese_br]', 'Proposta aceita pelo cliente', '<div>Ol&aacute;,<br /><br />O cliente <strong>{proposal_proposal_to}</strong> aceitou a proposta seguinte:<br /><br /><strong>N&uacute;mero:</strong> {proposal_number}<br /><strong>Assunto</strong>: {proposal_subject}<br /><strong>Total</strong>: {proposal_total}<br /><br />Visualize a proposta clicando no link: <a href=\"{proposal_link}\">{proposal_number}</a><br /><br />Sauda&ccedil;&otilde;es,<br />{email_signature}</div>\r\n<div>&nbsp;</div>\r\n<div>&nbsp;</div>\r\n<div>&nbsp;</div>', '{companyname} | CRM', '', 0, 1, 0),
(1335, 'proposals', 'proposal-send-to-customer', 'portuguese_br', 'Send Proposal to Customer [portuguese_br]', 'Proposta de número {proposal_number} Criada', 'Caro(a) {proposal_proposal_to}<br /><br />Por gentileza visualize nossa proposta em anexo.<br /><br />Esta proposta &eacute; v&aacute;lida at&eacute;:&nbsp;{proposal_open_till}<br /><br />Voc&ecirc; poder&aacute; visualizar a proposta atrav&eacute;s do link <a href=\"{proposal_link}\">{proposal_number}</a><br /><br />N&atilde;o hesite em comentar online se tiver qualquer d&uacute;vida.<br /><br />Estamos aguardando sua comunica&ccedil;&atilde;o.<br /><br />Sauda&ccedil;&otilde;es,<br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1336, 'proposals', 'proposal-client-declined', 'portuguese_br', 'Customer Action - Declined (Sent to Staff) [portuguese_br]', 'Cliente Recusou a Proposta', 'Ol&aacute;,<br /><br />O cliente <strong>{proposal_proposal_to}</strong> recusou a proposta <strong>{proposal_subject}</strong><br /><br />Visualize a proposta pelo do link <a href=\"{proposal_link}\">{proposal_number}</a> ou atrav&eacute;s da &aacute;rea administrativa.<br /><br />Sauda&ccedil;&otilde;es,<br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1337, 'proposals', 'proposal-client-thank-you', 'portuguese_br', 'Thank You Email (Sent to Customer After Accept) [portuguese_br]', 'Ficamos felizes que tenha aprovado a nossa proposta.', 'Prezado(a) {proposal_proposal_to}<br /><br />Ficamos felizes que tenha aprovado a nossa proposta.<br /><br />Estamos ansiosos para trabalhar com voc&ecirc;.<br /><br />Entraremos em contato o mais breve poss&iacute;vel<br /><br />Sauda&ccedil;&otilde;es,<br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1338, 'proposals', 'proposal-comment-to-client', 'portuguese_br', 'New Comment  (Sent to Customer/Lead) [portuguese_br]', 'Novo comentário à proposta', 'Prezado(a) {proposal_proposal_to}<br /><br />Um novo coment&aacute;rio foi feito sobre a seguinte proposta: <strong>{proposal_number}</strong><br /><br />Voc&ecirc; pode visualizar e responder ao coment&aacute;rio no seguinte link: <a href=\"{proposal_link}\">{proposal_number}</a><br /><br />Sauda&ccedil;&otilde;es,<br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1339, 'proposals', 'proposal-comment-to-admin', 'portuguese_br', 'New Comment (Sent to Staff)  [portuguese_br]', 'Novo comentário na proposta', 'Ol&aacute;,<br /><br />Um novo coment&aacute;rio foi feito &agrave; proposta <strong>{proposal_subject}</strong><br /><br />Voc&ecirc; pode visualizar e responder ao coment&aacute;rio no seguinte link: <a href=\"{proposal_link}\">{proposal_number}</a> ou atrav&eacute;s da &aacute;rea administrativa.<br /><br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1340, 'estimate', 'estimate-thank-you-to-customer', 'portuguese_br', 'Thank You Email (Sent to Customer After Accept) [portuguese_br]', 'Obrigado por aceitar o orçamento', '<span style=\"font-size: 12pt;\">Caro(a) {contact_firstname} {contact_lastname},</span><br /><br /><span style=\"font-size: 12pt;\">Obrigado por aceitar o or&ccedil;amento.</span><br /><br /><span style=\"font-size: 12pt;\">Entrarei em contato o mais breve poss&iacute;vel.</span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1341, 'tasks', 'task-deadline-notification', 'portuguese_br', 'Task Deadline Reminder - Sent to Assigned Members [portuguese_br]', 'Lembrete de data limite de tarefa', '<span style=\"font-size: 12pt;\"><span>Caro(a) {staff_firstname},<br /><br />Esta &eacute; uma mensagem autom&aacute;tica da &Aacute;rea do Cliente.<br /><br />A tarefa&nbsp;<strong>{task_name}, </strong>cuja data limite &eacute; <strong>{task_duedate}&nbsp;</strong>ainda n&atilde;o foi finalizada.<br /><br />Voc&ecirc; pode ver a tarefa no seguinte link</span>: <a href=\"{task_link}\">{task_name}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1342, 'contract', 'send-contract', 'portuguese_br', 'Send Contract to Customer [portuguese_br]', 'Contrato - {contract_subject}', '<span style=\"font-size: 12pt;\">Ol&aacute; {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">Por gentileza observe o {contract_subject} em anexo.<br /><br /></span>Estamos ansiosos pela sua devolutiva em rela&ccedil;&atilde;o ao contrato.<br /><br /><span style=\"font-size: 12pt;\">Sauda&ccedil;&otilde;es,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1343, 'invoice', 'invoice-payment-recorded-to-staff', 'portuguese_br', 'Invoice Payment Recorded (Sent to Staff) [portuguese_br]', 'Novo Pagamento de Fatura', '<span style=\"font-size: 12pt;\">Ol&aacute;,</span><br /><br /><span style=\"font-size: 12pt;\">O cliente&nbsp;<span>{client_company} pagou a fatura&nbsp;</span><strong># {invoice_number}</strong></span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; pode ver a fatura em: <a href=\"{invoice_link}\">{invoice_number}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1344, 'ticket', 'auto-close-ticket', 'portuguese_br', 'Auto Close Ticket [portuguese_br]', 'Solicitação Fechada Automaticamente', '<p><span style=\"font-size: 12pt;\">Ol&aacute; {contact_firstname} {contact_lastname},</span><br /><br /><span style=\"font-size: 12pt;\">A solicita&ccedil;&atilde;o {ticket_subject} foi fechada automaticamente devido &agrave; inatividade.</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Solicita&ccedil;&atilde;o #</strong>: <a href=\"{ticket_url}\">{ticket_id}</a></span><br /><span style=\"font-size: 12pt;\"><strong>Departmento</strong>: {ticket_department}</span><br /><span style=\"font-size: 12pt;\"><strong>Prioridade:</strong> {ticket_priority}</span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname} | CRM', '', 0, 1, 0),
(1345, 'project', 'new-project-discussion-created-to-staff', 'portuguese_br', 'New Project Discussion (Sent to Project Members) [portuguese_br]', 'Nova Conversa criada em Projeto - {project_name}', '<p>Ol&aacute; {staff_firstname}<br /><br />Uma nova conversa foi criada por&nbsp;<strong>{discussion_creator}</strong><br /><br /><strong>Assunto:</strong> {discussion_subject}<br /><strong>Descri&ccedil;&atilde;o:</strong> {discussion_description}<br /><br />Voc&ecirc; pode ver a conversa no seguinte link: <a href=\"{discussion_link}\">{discussion_subject}</a><br /><br />Atenciosamente,<br />{email_signature}</p>', '{companyname} | CRM', '', 0, 1, 0),
(1346, 'project', 'new-project-discussion-created-to-customer', 'portuguese_br', 'New Project Discussion (Sent to Customer Contacts) [portuguese_br]', 'Nova Conversa em Projeto criada - {project_name}', '<p>Ol&aacute; {contact_firstname} {contact_lastname},<br /><br />Uma nova conversa foi criada por&nbsp;<strong>{discussion_creator}</strong><br /><br /><strong>Assunto:</strong> {discussion_subject}<br /><strong>Descri&ccedil;&atilde;o:</strong> {discussion_description}<br /><br />Voc&ecirc; pode ver a conversa no seguinte link: <a href=\"{discussion_link}\">{discussion_subject}</a><br /><br />Atenciosamente,<br />{email_signature}</p>', '{companyname} | CRM', '', 0, 1, 0),
(1347, 'project', 'new-project-file-uploaded-to-customer', 'portuguese_br', 'New Project File(s) Uploaded (Sent to Customer Contacts) [portuguese_br]', 'Novo arquivo adicionado à projeto - {project_name}', '<p>Ol&aacute; {contact_firstname} {contact_lastname},<br /><br />Um novo arquivo foi anexo no projeto&nbsp;<strong>{project_name}</strong> por&nbsp;<strong>{file_creator}</strong><br /><br />Voc&ecirc; pode ver o projeto no seguinte link: <a href=\"{project_link}\">{project_name}</a><br /><br />Voc&ecirc; pode ver o arquivo na &Aacute;rea do Cliente pelo seguinte link: <a href=\"{discussion_link}\">{discussion_subject}</a><br /><br />Atenciosamente,<br />{email_signature}</p>', '{companyname} | CRM', '', 0, 1, 0),
(1348, 'project', 'new-project-file-uploaded-to-staff', 'portuguese_br', 'New Project File(s) Uploaded (Sent to Project Members) [portuguese_br]', 'Novo arquivo adicionado à projeto - {project_name}', '<p>Ol&aacute; {staff_firstname}</p>\r\n<p>Um novo arquivo foi enviado no projeto&nbsp;<strong>{project_name}</strong> por&nbsp;<strong>{file_creator}</strong></p>\r\n<p>Voc&ecirc; pode ver o projeto no seguinte link: <a href=\"{project_link}\">{project_name}<br /></a><br />Voc&ecirc; pode ver o arquivo no seguinte link: <a href=\"{discussion_link}\">{discussion_subject}</a></p>\r\n<p>Atenciosamente,<br />{email_signature}</p>', '{companyname} | CRM', '', 0, 1, 0),
(1349, 'project', 'new-project-discussion-comment-to-customer', 'portuguese_br', 'New Discussion Comment  (Sent to Customer Contacts) [portuguese_br]', 'Novo Comentário em Conversa', '<p><span style=\"font-size: 12pt;\">Ol&aacute; {contact_firstname} {contact_lastname},</span><br /><br /><span style=\"font-size: 12pt;\">Um novo coment&aacute;rio foi feito na Conversa com assunto&nbsp;<strong>{discussion_subject}</strong>, criado por<strong>{comment_creator}</strong></span><br /><br /><span style=\"font-size: 12pt;\"><strong>Assunto da conversa:</strong> {discussion_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Coment&aacute;rio</strong>: {discussion_comment}</span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; pode ver a conversa no link: <a href=\"{discussion_link}\">{discussion_subject}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname} | CRM', '', 0, 1, 0),
(1350, 'project', 'new-project-discussion-comment-to-staff', 'portuguese_br', 'New Discussion Comment (Sent to Project Members) [portuguese_br]', 'Novo Comentário em Conversa', '<p><span style=\"font-size: 12pt;\">Ol&aacute; {staff_firstname}</span><span style=\"font-size: 12pt;\">,</span></p>\r\n<p><br /><span style=\"font-size: 12pt;\">Um novo coment&aacute;rio foi feito na Conversa com assunto&nbsp;<strong>{discussion_subject}</strong>, criado por<strong>{comment_creator}</strong></span><br /><br /><span style=\"font-size: 12pt;\"><strong>Assunto da conversa:</strong> {discussion_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Coment&aacute;rio</strong>: {discussion_comment}</span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; pode ver a conversa no link: <a href=\"{discussion_link}\">{discussion_subject}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname} | CRM', '', 0, 1, 0),
(1351, 'project', 'staff-added-as-project-member', 'portuguese_br', 'Staff Added as Project Member [portuguese_br]', 'Novo Projeto designado à você', '<p>Ol&aacute; {staff_firstname},<br /><br />Um novo projeto foi designado &agrave; voc&ecirc;.<br /><br />Voc&ecirc; pode ver o projeto no seguinte link&nbsp;<a href=\"{project_link}\">{project_name}</a><br /><br />{email_signature}</p>', '{companyname} | CRM', '', 0, 1, 0),
(1352, 'estimate', 'estimate-expiry-reminder', 'portuguese_br', 'Estimate Expiration Reminder [portuguese_br]', 'Aviso de expiração de Orçamento', '<p><span style=\"font-size: 12pt;\">Ol&aacute; {client_company},</span><br /><br /><span style=\"font-size: 12pt;\">O or&ccedil;amento&nbsp;<strong># {estimate_number}</strong> ir&aacute; expirar em&nbsp;<strong>{estimate_expirydate}</strong></span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; pode aprovar o or&ccedil;amento no seguinte link: <a href=\"{estimate_link}\">{estimate_number}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname} | CRM', '', 0, 1, 0),
(1353, 'proposals', 'proposal-expiry-reminder', 'portuguese_br', 'Proposal Expiration Reminder [portuguese_br]', 'Proposal Expiration Reminder', '', '{companyname} | CRM', '', 0, 1, 0),
(1354, 'staff', 'new-staff-created', 'portuguese_br', 'New Staff Created (Welcome Email) [portuguese_br]', 'You are added as staff member', 'Ol&aacute; {staff_firstname}<br /><br />Voc&ecirc; foi adicionado como membro do nosso CRM.<br /><br />Por favor, use as seguintes credenciais:<br /><br /><strong>Email:</strong> {staff_email}<br /><strong>Senha:</strong> {password}<br /><br />Clique <a href=\"{admin_url}\">aqui</a> para fazer login na &aacute;rea administrativa.<br /><br />Sauda&ccedil;&otilde;es,<br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1355, 'client', 'contact-forgot-password', 'portuguese_br', 'Forgot Password [portuguese_br]', 'Criar Nova Senha', '<h2>Criar uma nova senha</h2>\r\nEsqueceu sua senha?<br />Para criar uma nova senha, clique no link:<br /><br /><a href=\"{reset_password_url}\">Resetar Senha</a><br /><br />Voc&ecirc; recebeu este email pois algu&eacute;m solicitou um reset de senha no CRM. Se voc&ecirc; n&atilde;o solicitou este reset, por favor ignore este email.<br /><br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1356, 'client', 'contact-password-reseted', 'portuguese_br', 'Password Reset - Confirmation [portuguese_br]', 'Sua senha foi alterada', '<strong><span style=\"font-size: 14pt;\">Voc&ecirc; trocou sua senha.</span><br /></strong><br />Por favor, anote em lugar seguro para n&atilde;o esquecer.<br /><br />Seu endere&ccedil;o de email para login &eacute;: {contact_email}<br /><br />Se voc&ecirc; n&atilde;o solicitou esta troca de senha, por favor entre em contato comigo.<br /><br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1357, 'client', 'contact-set-password', 'portuguese_br', 'Set New Password [portuguese_br]', 'Defina uma nova senha para o acesso à Área do Cliente', '<h2>Defina uma nova senha para o acesso &agrave; &Aacute;rea do Cliente</h2>\r\nPor favor, use o seguinte link para definir sua nova senha:<br /><br /><a href=\"{set_password_url}\">Definir nova senha</a><br /><br />Por favor, anote em um lugar seguro para n&atilde;o se esquecer.<br /><br />Lembre-se que o link acima ir&aacute; expirar em <strong>48 horas</strong>. Depois deste per&iacute;odo, o link se tornar&aacute; inv&aacute;lido.<br /><br />Voc&ecirc; pode fazer o link em: <a href=\"{crm_url}\">{crm_url}</a><br />Seu email para login: {contact_email}<br /><br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1358, 'staff', 'staff-forgot-password', 'portuguese_br', 'Forgot Password [portuguese_br]', 'Criar nova senha', '<h2><span style=\"font-size: 14pt;\">Criar nova senha.</span></h2>\r\nEsqueceu sua senha<br />Para criar uma nova senha clique no link abaixo:<br /><br /><a href=\"{reset_password_url}\">Resetar Senha</a><br /><br />Voc&ecirc; recebeu este e-mail porque foi solicitado por um usu&aacute;rio da <strong>{companyname}</strong>. Isso faz parte do procedimento para criar uma nova senha no sistema. Se voc&ecirc; N&Atilde;O solicitou uma nova senha, ignore este e-mail e sua senha permanecer&aacute; a mesma.<br /><br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1359, 'staff', 'staff-password-reseted', 'portuguese_br', 'Password Reset - Confirmation [portuguese_br]', 'Você mudou sua senha', '<span style=\"font-size: 14pt;\"><strong>Voc&ecirc; mudou sua senha.<br /></strong></span><br />Mantenha-o em seus registros para n&atilde;o esquec&ecirc;-lo. <br /><br />Seu endere&ccedil;o de e-mail para login &eacute;: {staff_email}<br /><br />Se n&atilde;o foi voc&ecirc;, entre em contato conosco.<br /><br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1360, 'project', 'assigned-to-project', 'portuguese_br', 'New Project Created (Sent to Customer Contacts) [portuguese_br]', 'Novo Projeto Criado', '<p>Ol&aacute; {contact_firstname}&nbsp;{contact_lastname},</p>\r\n<p>Um novo projeto foi adicionado para a sua empresa.<br /><br /><strong>Nome do Projeto:</strong>&nbsp;{project_name}<br /><strong>Data de In&iacute;cio do Projeto:</strong>&nbsp;{project_start_date}</p>\r\n<p>Voc&ecirc; pode acompanhar o projeto no seguinte link:&nbsp;<a href=\"{project_link}\">{project_name}</a></p>\r\n<p>Agradecemos sua participa&ccedil;&atilde;o.<br /><br />Atenciosamente,<br />{email_signature}</p>', '{companyname} | CRM', '', 0, 1, 0),
(1361, 'tasks', 'task-added-attachment-to-contacts', 'portuguese_br', 'New Attachment(s) on Task (Sent to Customer Contacts) [portuguese_br]', 'Novo anexo em tarefa - {task_name}', '<span style=\"font-size: 12pt;\"><span>Caro(a) {contact_firstname} {contact_lastname},<br /><br /><strong>{task_user_take_action}</strong>&nbsp;adicionou um anexo na seguinte tarefa:<br /><br /><strong>Nome:</strong> {task_name}<br /><br />Voc&ecirc; pode ver a tarefa no seguinte link</span>: <a href=\"{task_link}\">{task_name}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1362, 'tasks', 'task-commented-to-contacts', 'portuguese_br', 'New Comment on Task (Sent to Customer Contacts) [portuguese_br]', 'Novo comentário na tarefa - {task_name}', '<span style=\"font-size: 12pt;\"><span>Caro(a) {contact_firstname} {contact_lastname},<br /><br />Um coment&aacute;rio foi feito na seguinte tarefa:<br /><br /><strong>Nome:</strong> {task_name}<br /><strong>Coment&aacute;rio:</strong> {task_comment}<br /><br />Voc&ecirc; pode ver a tarefa no seguinte link</span>: <a href=\"{task_link}\">{task_name}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1363, 'leads', 'new-lead-assigned', 'portuguese_br', 'New Lead Assigned to Staff Member [portuguese_br]', 'Novo lead designado à você', '<p>Ol&aacute; {lead_assigned},<br /><br />Um novo lead foi designado &agrave; voc&ecirc;.<br /><br />Nome:&nbsp;<span class=\"pull-right\"><a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{lead_name}</a></span><br />Email:&nbsp;<span class=\"pull-right\"><a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{lead_email}</a></span><br /><span class=\"pull-right\">Interesse:&nbsp;<a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{leads_interesse_em}</a></span><br />Cargo:&nbsp;<span class=\"pull-right\"><a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{lead_position}</a></span><span class=\"pull-right\"><a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\"></a></span><span class=\"pull-right\"><a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\"></a></span><br /><span class=\"pull-right\">Telefone:&nbsp;<a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{lead_phonenumber}</a></span><br />Empresa:&nbsp;<span class=\"pull-right\"><a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{lead_company}</a></span><br /><span class=\"pull-right\">Mensagem:<a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{lead_description}</a></span><br /><br />Voc&ecirc; pode ver o lead no seguinte link: <a href=\"{lead_link}\">{lead_name}</a><br /><br />Atenciosamente,<br />{email_signature}</p>', '{companyname} | CRM', '', 0, 1, 0),
(1364, 'client', 'client-statement', 'portuguese_br', 'Statement - Account Summary [portuguese_br]', 'Balanço da conta entre {statement_from} e {statement_to}', 'Caro(a) {contact_firstname} {contact_lastname}, <br /><br />Foi uma exclente experi&ecirc;ncia trabalhar com voc&ecirc;.<br /><br />Em anexo neste email est&aacute; a lista de todas as transa&ccedil;&otilde;es no per&iacute;odo entre {statement_from} at&eacute; {statement_to}.<br /><br />O balan&ccedil;o geral da sua conta &eacute;:&nbsp;{statement_balance_due}<br /><br />Por favor entre em contato conosco se precisar de maiores informa&ccedil;&otilde;es.<br /><br />Atenciosamente,<br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1365, 'ticket', 'ticket-assigned-to-admin', 'portuguese_br', 'New Ticket Assigned (Sent to Staff) [portuguese_br]', 'Uma nova solicitação foi designada à você', '<p><span style=\"font-size: 12pt;\">Ol&aacute;,</span></p>\r\n<p><span style=\"font-size: 12pt;\">Uma nova solicita&ccedil;&atilde;o foi designada &agrave; voc&ecirc;.</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Assunto</strong>: {ticket_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Departmento</strong>: {ticket_department}</span><br /><span style=\"font-size: 12pt;\"><strong>Prioridade</strong>: {ticket_priority}</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Mensagem:</strong></span><br /><span style=\"font-size: 12pt;\">{ticket_message}</span><br /><br /><span style=\"font-size: 12pt;\">Voc&ecirc; pode acompanhar a solicita&ccedil;&atilde;o no seguinte link: <a href=\"{ticket_url}\">#{ticket_id}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname} | CRM', '', 0, 1, 0),
(1366, 'client', 'new-client-registered-to-admin', 'portuguese_br', 'New Customer Registration (Sent to admins) [portuguese_br]', 'Novo Cliente Registrado', 'Ol&aacute;.<br /><br />Um novo cliente se registrou na sua &aacute;rea do cliente:<br /><br /><strong>Primeiro nome:</strong>&nbsp;{contact_firstname}<br /><strong>Sobrenome:</strong>&nbsp;{contact_lastname}<br /><strong>Empresa:</strong>&nbsp;{client_company}<br /><strong>Email:</strong>&nbsp;{contact_email}<br /><br />Atenciosamente.', '{companyname} | CRM', '', 0, 1, 0),
(1367, 'leads', 'new-web-to-lead-form-submitted', 'portuguese_br', 'Web to lead form submitted - Sent to lead [portuguese_br]', '{lead_name} - Seu pedido de orçamento foi recebido', 'Ol&aacute; {lead_name},<br /><br /><strong>Este e-mail &eacute; s&oacute; para confirmar que sua solicita&ccedil;&atilde;o de or&ccedil;amento foi recebida.</strong><br /><br />\r\n<div class=\"col-md-6 merge_fields_col\">Nome:&nbsp;<span class=\"pull-right\"><a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{lead_name}</a></span><br />Email:&nbsp;<span class=\"pull-right\"><a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{lead_email}</a></span><br /><span class=\"pull-right\">Interesse:&nbsp;<a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{leads_interesse_em}</a></span><br />Cargo:&nbsp;<span class=\"pull-right\"><a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{lead_position}</a></span><span class=\"pull-right\"><a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\"></a></span><span class=\"pull-right\"><a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\"></a></span><br /><span class=\"pull-right\">Telefone:&nbsp;<a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{lead_phonenumber}</a></span><br />Empresa:&nbsp;<span class=\"pull-right\"><a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{lead_company}</a></span><br /><span class=\"pull-right\">Mensagem:<a href=\"https://crm.lucasbustamante.com.br/admin/emails/email_template/53#\" class=\"add_merge_field\">{lead_description}</a><br /></span></div>\r\n<br />Irei responder em breve.<br /><br />Atenciosamente,<br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1368, 'staff', 'two-factor-authentication', 'portuguese_br', 'Two Factor Authentication [portuguese_br]', 'Confirme o seu login', '<p>Ol&aacute; {staff_firstname}</p>\r\n<p style=\"text-align: left;\">Voc&ecirc; recebeu este e-mail porque ativou a autentica&ccedil;&atilde;o de dois fatores em sua conta.<br /><br />Use o c&oacute;digo a seguir para confirmar seu login:</p>\r\n<p style=\"text-align: left;\"><span style=\"font-size: 18pt;\"><strong>{two_factor_auth_code}<br /><br /></strong><span style=\"font-size: 12pt;\">{email_signature}</span><strong><br /><br /><br /><br /></strong></span></p>', '{companyname} | CRM', '', 0, 1, 0),
(1369, 'project', 'project-finished-to-customer', 'portuguese_br', 'Project Marked as Finished (Sent to Customer Contacts) [portuguese_br]', 'Projeto Concluído', '<p>Ol&aacute; {contact_firstname}&nbsp;{contact_lastname},</p>\r\n<p>Voc&ecirc; est&aacute; recebendo este email pois o projeto&nbsp;<strong>{project_name}</strong>&nbsp;foi marcado como Conclu&iacute;do. Este projeto estava assimilado &agrave; sua empresa, e s&oacute; queria te manter informado.<br /><br />Voc&ecirc; pode ver detalhes do projeto no seguinte link:&nbsp;<a href=\"{project_link}\">{project_name}</a></p>\r\n<p>Se voc&ecirc; tiver qualquer d&uacute;vida n&atilde;o hesite em entrar em contato conosco.<br /><br />Atenciosamente,<br />{email_signature}</p>', '{companyname} | CRM', '', 0, 1, 0),
(1370, 'credit_note', 'credit-note-send-to-client', 'portuguese_br', 'Send Credit Note To Email [portuguese_br]', 'Nota de Crédito #{credit_note_number} Criada', 'Caro(a) {contact_firstname}&nbsp;{contact_lastname},<br /><br />Segue em anexo a nota de cr&eacute;dito&nbsp;<strong>#{credit_note_number}</strong>.<br /><br /><strong>Data:</strong>&nbsp;{credit_note_date}<br /><strong>Valor:</strong>&nbsp;{credit_note_total}<br /><br /><span style=\"font-size: 12pt;\">Por favor entre em contato conosco em caso de d&uacute;vidas.</span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1371, 'tasks', 'task-status-change-to-staff', 'portuguese_br', 'Task Status Changed (Sent to Staff) [portuguese_br]', 'Status da Tarefa Alterado', '<span style=\"font-size: 12pt;\"><span>Caro(a) {staff_firstname},<br /><br /><strong>{task_user_take_action}</strong>&nbsp;marcou a tarefa como&nbsp;<strong>{task_status}</strong><br /><br /><strong>Nome:</strong> {task_name}<br /><strong>Data Limite:</strong> {task_duedate}<br /><br />Voc&ecirc; pode ver a tarefa no seguinte link</span>: <a href=\"{task_link}\">{task_name}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1372, 'tasks', 'task-status-change-to-contacts', 'portuguese_br', 'Task Status Changed (Sent to Customer Contacts) [portuguese_br]', 'Status da Tarefa Alterado', '<span style=\"font-size: 12pt;\"><span>Caro(a) {contact_firstname} {contact_lastname},<br /><br /><strong>{task_user_take_action}</strong>&nbsp;marcou a tarefa como&nbsp;<strong>{task_status}</strong><br /><br /><strong>Nome:</strong> {task_name}<br /><strong>Data Limite:</strong> {task_duedate}<br /><br />Voc&ecirc; pode ver a tarefa no seguinte link</span>: <a href=\"{task_link}\">{task_name}</a></span><br /><br /><span style=\"font-size: 12pt;\">Atenciosamente,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1373, 'staff', 'reminder-email-staff', 'portuguese_br', 'Staff Reminder Email [portuguese_br]', 'Você tem um novo lembrete!', 'Ol&aacute; {staff_firstname}<br /><br /><strong>Voc&ecirc; tem um novo lembrete vinculado a {staff_reminder_relation_name}!<br /><br />Descri&ccedil;&atilde;o do lembrete:</strong><br />{staff_reminder_description}<br /><br />Clique <a href=\"{staff_reminder_relation_link}\">aqui</a> par visualizar <a href=\"{staff_reminder_relation_link}\">{staff_reminder_relation_name}</a><br /><br />Sauda&ccedil;&otilde;es', '{companyname} | CRM', '', 0, 1, 0),
(1374, 'contract', 'contract-comment-to-client', 'portuguese_br', 'New Comment  (Sent to Customer Contacts) [portuguese_br]', 'Novo comentário ao contrato', 'Prezado(a) {contact_firstname} {contact_lastname}<br /><br />Um novo coment&aacute;rio foi feito sobre o contrato a seguir: <strong>{contract_subject}</strong><br /><br />Voc&ecirc; pode visualizar e responder ao coment&aacute;rio no seguinte link: <a href=\"{contract_link}\">{contract_subject}</a><br /><br />Sauda&ccedil;&otilde;es,<br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1375, 'contract', 'contract-comment-to-admin', 'portuguese_br', 'New Comment (Sent to Staff)  [portuguese_br]', 'Novo comentário ao contrato', 'Ol&aacute; {staff_firstname}<br /><br />Um novo coment&aacute;rio foi feito ao contrato <strong>{contract_subject}</strong><br /><br />Voc&ecirc; pode visualizar e responder ao coment&aacute;rio no seguinte link: <a href=\"{contract_link}\">{contract_subject}</a> ou atrav&eacute;s da &aacute;rea administrativa<br /><br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1376, 'subscriptions', 'send-subscription', 'portuguese_br', 'Send Subscription to Customer [portuguese_br]', 'Subscription Created', 'Caro(a) {contact_firstname} {contact_lastname},<br /><br />Preparamos uma assinatura <strong>{subscription_name} </strong>para seu neg&oacute;cio.<br /><br />Clique <a href=\"{subscription_link}\" target=\"_blank\" rel=\"noopener\">aqui</a> para revisar a assinatura e confirmar.<br /><br />Com muita satisfa&ccedil;&atilde;o, <br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1377, 'subscriptions', 'subscription-payment-failed', 'portuguese_br', 'Subscription Payment Failed [portuguese_br]', 'Seu pagamento mais recente falhou', 'Ol&aacute; {contact_firstname} {contact_lastname},<br /><br />Infelizmente, o seu pagamento de fatura mais recente para <strong>{subscription_name} </strong>foi rejeitado pela operadora.<br /><br />Pode ter ocorrido alguma mudan&ccedil;a no seu n&uacute;mero de cart&atilde;o, seu cart&atilde;o pode ter expirado, cancelado ou ainda a operadora do cart&atilde;o n&atilde;o ter reconhecido a transa&ccedil;&atilde;o e a bloqueado.<br /><br />Por favor atualize suas informa&ccedil;&otilde;es de pagamento o mais brevemente poss&iacute;vel, fazendo login aqui: <a href=\"{crm_url}\">{crm_url}</a><br /><br />Com muita satisfa&ccedil;&atilde;o, <br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1378, 'subscriptions', 'subscription-canceled', 'portuguese_br', 'Subscription Canceled (Sent to customer primary contact) [portuguese_br]', 'Your subscription has been canceled', 'Ol&aacute; {contact_firstname} {contact_lastname},<br /><br />Sua assinatura <strong>{subscription_name} </strong>foi cancelada, se voc&ecirc; tem alguma d&uacute;vida n&atilde;o hesite em nos contatar.<br /><br />Foi um prazer ter feito neg&oacute;cios com voc&ecirc;.<br /><br />Com muita satisfa&ccedil;&atilde;o, <br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1379, 'subscriptions', 'subscription-payment-succeeded', 'portuguese_br', 'Subscription Payment Succeeded (Sent to customer primary contact) [portuguese_br]', 'Assinatura Pagamento Recebido - {subscription_name}', 'Ol&aacute; {contact_firstname} {contact_lastname},<br /><br />Este e-mail &eacute; para informar que recebemos seu pagamento para a assinatura <strong>{subscription_name} </strong>no valor de <strong><span>{payment_total}</span></strong><br /><br />A fatura associada est&aacute; com status <strong>{invoice_status}</strong><br /><br />Obrigado por sua confian&ccedil;a.<br /><br />Com muita satisfa&ccedil;&atilde;o, <br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0);
INSERT INTO `tblemailtemplates` (`emailtemplateid`, `type`, `slug`, `language`, `name`, `subject`, `message`, `fromname`, `fromemail`, `plaintext`, `active`, `order`) VALUES
(1380, 'contract', 'contract-expiration-to-staff', 'portuguese_br', 'Contract Expiration Reminder (Sent to Staff) [portuguese_br]', 'Lembrete de expiração do contrato', 'Ol&aacute; {staff_firstname}<br /><br />Este &eacute; um lembrete de que o contrato a seguir expirar&aacute; em breve:<br /><br /><span style=\"font-size: 12pt;\"><strong>Assunto:</strong> {contract_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Descri&ccedil;&atilde;o:</strong> {contract_description}</span><br /><span style=\"font-size: 12pt;\"><strong>Data de In&iacute;cio:</strong> {contract_datestart}</span><br /><span style=\"font-size: 12pt;\"><strong>Data de Conclus&atilde;o:</strong> {contract_dateend}</span><br /><br /><span style=\"font-size: 12pt;\">Sauda&ccedil;&otilde;es,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(1381, 'gdpr', 'gdpr-removal-request', 'portuguese_br', 'Removal Request From Contact (Sent to administrators) [portuguese_br]', 'Data Removal Request Received', '', '{companyname} | CRM', NULL, 0, 1, 0),
(1382, 'gdpr', 'gdpr-removal-request-lead', 'portuguese_br', 'Removal Request From Lead (Sent to administrators) [portuguese_br]', 'Data Removal Request Received', '', '{companyname} | CRM', NULL, 0, 1, 0),
(1383, 'client', 'client-registration-confirmed', 'portuguese_br', 'Customer Registration Confirmed [portuguese_br]', 'Sua conta na Área do Cliente está confirmada', '<p>Caro(a) {contact_firstname} {contact_lastname},<br /><br />&Eacute; com satisfa&ccedil;&atilde;o que lhe informo que sua conta na &Aacute;rea do Cliente foi confirmada e est&aacute; agora ativa.<br /><br />Voc&ecirc; pode logar na URL&nbsp;<a href=\"{crm_url}\">{crm_url}</a>&nbsp;com o email e senha informados durante a cria&ccedil;&atilde;o da conta.<br /><br />Por favor, entre em contato conosco se precisar de qualquer coisa.<br /><br />(Este &eacute; um e-mail autom&aacute;tico, por favor n&atilde;o responda &agrave; esta mensagem)<br /><br />Atenciosamente, <br />{email_signature}</p>', '{companyname} | CRM', '', 0, 1, 0),
(1384, 'contract', 'contract-signed-to-staff', 'portuguese_br', 'Contract Signed (Sent to Staff) [portuguese_br]', 'O cliente assinou um contrato', 'Ol&aacute; {staff_firstname}<br /><br />Um contrato com o assunto <strong>{contract_subject} </strong>foi assinado com sucesso pelo cliente.<br /><br />Voc&ecirc; pode visualizar o contrato no seguinte link: <a href=\"{contract_link}\">{contract_subject}</a> ou da &aacute;rea de administra&ccedil;&atilde;o.<br /><br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1385, 'subscriptions', 'customer-subscribed-to-staff', 'portuguese_br', 'Customer Subscribed to a Subscription (Sent to administrators and subscription creator) [portuguese_br]', 'Cliente confirmou uma Assinatura', 'O cliente <strong>{client_company} </strong>confirmou a assinatura com o nome <strong>{subscription_name}</strong><br /><br /><strong>ID</strong>:&nbsp;{subscription_id}<br /><strong>Nome da assinatura</strong>:&nbsp;{subscription_name}<br /><strong>Descri&ccedil;&atilde;o da Assinatura</strong>:&nbsp;{subscription_description}<br /><br />Voc&ecirc; pode ver a assinatura clicando <a href=\"{subscription_link}\">aqui</a><br /><br /><br />Com muita satisfa&ccedil;&atilde;o, <br />{email_signature}<br /><br /><span style=\"font-size: 10pt;\"><span style=\"color: #999999;\">Voc&ecirc; est&aacute; recebendo este e-mail porque &eacute; o administrador ou o criador da assinatura.</span></span>', '{companyname} | CRM', '', 0, 1, 0),
(1386, 'client', 'contact-verification-email', 'portuguese_br', 'Email Verification (Sent to Contact After Registration) [portuguese_br]', 'Verifique o endereço de email', '<p>Ol&aacute; {contact_firstname},<br /><br />Por favor, clique no link abaixo para verificar seu e-mail:<br /><br /><a href=\"{email_verification_url}\">Verificar endere&ccedil;o de email</a><br /><br />Se voc&ecirc; n&atilde;o criou esta conta, por favor ignore este email.</p>\r\n<p><br />Atenciosamente,<br />{email_signature}</p>', '{companyname} | CRM', '', 0, 1, 0),
(1387, 'client', 'new-customer-profile-file-uploaded-to-staff', 'portuguese_br', 'New Customer Profile File(s) Uploaded (Sent to Staff) [portuguese_br]', 'Cliente enviou novos arquivos no perfil', 'Ol&aacute;!<br /><br />Novo(s) arquivo(s) enviado(s) para o perfil do cliente ({client_company}) por {contact_firstname}<br /><br />Voc&ecirc; pode verificar os arquivos enviados na &aacute;rea administrativa clicando <a href=\"{customer_profile_files_admin_link}\" target=\"_blank\" rel=\"noopener\">aqui</a> ou atrav&eacute;s do seguinte link: {customer_profile_files_admin_link}<br /><br />{email_signature}', '{companyname} | CRM', '', 0, 1, 0),
(1481, 'subscriptions', 'subscription-payment-requires-action', 'portuguese_br', 'Credit Card Authorization Required - SCA [portuguese_br]', 'Important: Confirm your subscription {subscription_name} payment', '', '{companyname} | CRM', NULL, 0, 1, 0);

--
-- Índices de tabelas apagadas
--

--
-- Índices de tabela `tblemailtemplates`
--
ALTER TABLE `tblemailtemplates`
  ADD PRIMARY KEY (`emailtemplateid`);

--
-- AUTO_INCREMENT de tabelas apagadas
--

--
-- AUTO_INCREMENT de tabela `tblemailtemplates`
--
ALTER TABLE `tblemailtemplates`
  MODIFY `emailtemplateid` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1566;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
